### ISSUE TITLE
Position tracking of headers is inconsistent

### ISSUE THREAD

**Issue by neongreen** [jgm/cmark-hs#9]

**Comment by neongreen** [comment]
Ouch, accidentally pressed Enter.

Position info for a `#`-style header doesn't include the `#` (i.e. it starts from column 3 instead of column 1):

``` haskell
> let Node _ DOCUMENT [n] = commonmarkToNode [] (T.pack "# hello") in n

Node (Just (PosInfo {startLine = 1, 
                     startColumn = 3, 
                     endLine = 1, 
                     endColumn = 7})) 
     (HEADING 1) 
     [Node Nothing (TEXT "hello") []]
```

Position info for a `=====`-style header _does_ include the `=====` (i.e. it ends at line 2, not line 1):

``` haskell
> let Node _ DOCUMENT [n] = commonmarkToNode [] (T.pack "hello\n=====") in n

Node (Just (PosInfo {startLine = 1, 
                     startColumn = 1,
                     endLine = 2,
                     endColumn = 5})) 
     (HEADING 1)
     [Node Nothing (TEXT "hello") []]
```

The latter behavior seems more correct to me and it'd be good if source positions for `#`-style headers behaved the same way.

**Comment by neongreen** [comment]
Hm, it just occurred to me. Should I move this issue to jgm/cmark?

**Comment by jgm** [comment]
Yes.

+++ Artyom [Jul 07 16 13:02 ]:

>   Hm, it just occurred to me. Should I move this issue to jgm/cmark?
